import type { Profile } from "@/routes/_authenticated/discover";

export interface HangoutItem {
  id: string;
  title: string;
  details: string;
  current_city: string;
  date_time: string;
  created_by_name: string;
  created_by_avatar?: string;
  category: "cookoff" | "tandem" | "study" | "casual";
  created_at?: string;
}

export const DIVERSE_PROFILES: Profile[] = [
  {
    id: "p-native-1",
    name: "Maximilian Bauer",
    home_country: "Germany",
    home_city: "Munich",
    current_country: "Germany",
    current_city: "Munich",
    current_area: "Maxvorstadt",
    university: "Technical University of Munich (TUM)",
    bio: "Born and raised in Munich! TUM alumnus and local guide. Ask me anything about city registration, finding apartments, local bakery spots, or Bavarian culture.",
    avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    instagram: "max_munich_native",
    whatsapp: "+491719876543",
    linkedin: "max-bauer-munich",
    twitter: null,
    website: null,
    is_buddy: true,
    is_native: true,
    relocation_type: "native",
    major: "Mechanical Engineering",
    arrival_date: "2010-01-01",
    favorite_dish: "Kässpätzle & Pretzel",
    languages_spoken: "German, English, French",
    languages_learning: "Spanish",
    study_interests: "Automotive Engineering, Urban Transit",
    kudos_count: 89,
    honor_title: "Verified Native Host",
  },
  {
    id: "p-native-2",
    name: "Chloe Dubois",
    home_country: "France",
    home_city: "Paris",
    current_country: "France",
    current_city: "Paris",
    current_area: "Le Marais",
    university: "Sorbonne University",
    bio: "Parisian native living here my entire life. Happy to assist international students and domestic shifters with CAF housing paperwork, transport, and local bakeries.",
    avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    instagram: "chloe_paris_local",
    whatsapp: "+33699887766",
    linkedin: "chloe-dubois-paris",
    twitter: null,
    website: null,
    is_buddy: true,
    is_native: true,
    relocation_type: "native",
    major: "History of Art",
    arrival_date: "2012-01-01",
    favorite_dish: "Croissant & Ratatouille",
    languages_spoken: "French, English, Italian",
    languages_learning: "German",
    study_interests: "Art History, Museum Curation",
    kudos_count: 76,
    honor_title: "Local Paris Ambassador",
  },
  {
    id: "p-national-1",
    name: "Rohan Verma",
    home_country: "India",
    home_city: "Mumbai",
    current_country: "India",
    current_city: "Delhi",
    current_area: "Connaught Place",
    university: "Delhi University",
    bio: "Relocated from Mumbai to Delhi for my Master's degree in Public Policy. Love helping domestic interstate movers adapt to new cities within India!",
    avatar_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80",
    instagram: "rohan_delhi_move",
    whatsapp: "+919876543210",
    linkedin: "rohan-verma-policy",
    twitter: null,
    website: null,
    is_buddy: true,
    is_native: false,
    relocation_type: "national",
    major: "Public Policy",
    arrival_date: "2025-07-15",
    favorite_dish: "Vada Pav & Chole Bhature",
    languages_spoken: "Hindi, English, Marathi",
    languages_learning: "Punjabi",
    study_interests: "Urban Governance, Public Health",
    kudos_count: 52,
    honor_title: "National Transfer Buddy",
  },
  {
    id: "p-1",
    name: "Aarav Sharma",
    home_country: "India",
    home_city: "Mumbai",
    current_country: "Germany",
    current_city: "Munich",
    current_area: "Maxvorstadt",
    university: "Technical University of Munich (TUM)",
    bio: "M.Sc. Computer Science student passionate about AI & robotics. Love street food, cricket, and weekend hiking in the Alps!",
    avatar_url: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80",
    instagram: "aarav_mumbai",
    whatsapp: "+4915123456781",
    linkedin: "aarav-sharma-tum",
    twitter: null,
    website: null,
    is_buddy: true,
    is_native: false,
    relocation_type: "international",
    major: "Computer Science",
    arrival_date: "2025-09-01",
    favorite_dish: "Butter Chicken & Biryani",
    languages_spoken: "Hindi, English, Marathi",
    languages_learning: "German, French",
    study_interests: "Artificial Intelligence, Algorithms, Machine Learning",
    kudos_count: 64,
    honor_title: "Community Pillar",
  },
  {
    id: "p-2",
    name: "Sophia Chen",
    home_country: "China",
    home_city: "Shanghai",
    current_country: "United Kingdom",
    current_city: "London",
    current_area: "South Kensington",
    university: "Imperial College London",
    bio: "Finance & Data Analytics postgrad. Miss Shanghai dumplings! Always down for tea tastings and museum walks in South Kensington.",
    avatar_url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    instagram: "sophia_shanghai",
    whatsapp: "+447700900123",
    linkedin: "sophiachen-imperial",
    twitter: null,
    website: null,
    is_buddy: true,
    major: "Financial Technology",
    arrival_date: "2025-10-05",
    favorite_dish: "Dim Sum & Xiao Long Bao",
    languages_spoken: "Mandarin, Cantonese, English",
    languages_learning: "French, Italian",
    study_interests: "Fintech, Quantitative Finance, Python",
    kudos_count: 58,
    honor_title: "Cultural Mentor",
  },
  {
    id: "p-3",
    name: "Mateo Rossi",
    home_country: "Italy",
    home_city: "Milan",
    current_country: "United States",
    current_city: "New York",
    current_area: "Manhattan",
    university: "Columbia University",
    bio: "Architecture & Urban Design student in Manhattan. Passionate about sustainable city planning, espresso, and indie cinema.",
    avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    instagram: "mateorossi_nyc",
    whatsapp: "+12125550198",
    linkedin: "mateorossi-arch",
    twitter: null,
    website: null,
    is_buddy: false,
    major: "Architecture",
    arrival_date: "2025-08-20",
    favorite_dish: "Tagliatelle al Ragù & Pizza Margherita",
    languages_spoken: "Italian, English",
    languages_learning: "Spanish, German",
    study_interests: "Sustainable Design, Urban Planning, CAD",
    kudos_count: 49,
    honor_title: "Neighborhood Navigator",
  },
  {
    id: "p-4",
    name: "Camila Benitez",
    home_country: "Mexico",
    home_city: "Mexico City",
    current_country: "Spain",
    current_city: "Barcelona",
    current_area: "Gràcia",
    university: "Universitat de Barcelona",
    bio: "International Law student exploring Catalan culture. Let's make authentic tacos and practice languages over tapas!",
    avatar_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    instagram: "camila_bcn",
    whatsapp: "+34612345678",
    linkedin: "camila-benitez-law",
    twitter: null,
    website: null,
    is_buddy: true,
    major: "International Law",
    arrival_date: "2025-09-15",
    favorite_dish: "Tacos al Pastor & Chilaquiles",
    languages_spoken: "Spanish, English",
    languages_learning: "Catalan, French",
    study_interests: "Human Rights, Public Law, International Relations",
    kudos_count: 42,
    honor_title: "Peer Ambassador",
  },
  {
    id: "p-5",
    name: "Kenji Takahashi",
    home_country: "Japan",
    home_city: "Tokyo",
    current_country: "Canada",
    current_city: "Toronto",
    university: "University of Toronto",
    bio: "Robotics & Mechatronics Engineering. Big fan of Toronto coffee shops, snowboarding, and cooking ramen for friends.",
    avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    instagram: "kenji_uoft",
    whatsapp: "+14165550147",
    linkedin: "kenji-takahashi-eng",
    twitter: null,
    website: null,
    is_buddy: true,
    major: "Robotics Engineering",
    arrival_date: "2025-09-02",
    favorite_dish: "Tonkotsu Ramen & Matcha Parfait",
    languages_spoken: "Japanese, English",
    languages_learning: "French",
    study_interests: "Robotics, Mechatronics, Embedded Systems",
  },
  {
    id: "p-6",
    name: "Fatima Al-Hassan",
    home_country: "United Arab Emirates",
    home_city: "Dubai",
    current_country: "France",
    current_city: "Paris",
    university: "Sorbonne University",
    bio: "Fashion Design & Luxury Brand Management. Exploring Parisian bakeries, art galleries, and organizing international dinner circles.",
    avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    instagram: "fatima_in_paris",
    whatsapp: "+33612345679",
    linkedin: "fatima-alhassan-luxury",
    twitter: null,
    website: null,
    is_buddy: true,
    major: "Luxury Management",
    arrival_date: "2025-09-10",
    favorite_dish: "Luqaimat & Shawarma",
    languages_spoken: "Arabic, English, French",
    languages_learning: "Italian",
    study_interests: "Fashion Industry, Marketing, Consumer Behavior",
  },
  {
    id: "p-7",
    name: "Amara Okonkwo",
    home_country: "Nigeria",
    home_city: "Lagos",
    current_country: "United States",
    current_city: "Boston",
    university: "Harvard University / MIT",
    bio: "Biomedical Engineering researcher. Passionate about healthtech, Afrobeats dance workshops, and cooking spicy Jollof rice!",
    avatar_url: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&auto=format&fit=crop&q=80",
    instagram: "amara_boston",
    whatsapp: "+16175550188",
    linkedin: "amara-okonkwo-bio",
    twitter: null,
    website: null,
    is_buddy: true,
    major: "Biomedical Engineering",
    arrival_date: "2025-08-25",
    favorite_dish: "Jollof Rice & Fried Plantains",
    languages_spoken: "English, Yoruba, Igbo",
    languages_learning: "Spanish",
    study_interests: "Bioinformatics, Medical Devices, Genetics",
  },
  {
    id: "p-8",
    name: "Lukas Weber",
    home_country: "Germany",
    home_city: "Berlin",
    current_country: "Australia",
    current_city: "Sydney",
    university: "University of Sydney",
    bio: "Marine Biology student loving Bondi Beach & coastal walks. Looking for study buddies for oceanography exams!",
    avatar_url: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80",
    instagram: "lukas_sydney",
    whatsapp: "+61412345678",
    linkedin: "lukas-weber-marine",
    twitter: null,
    website: null,
    is_buddy: false,
    major: "Marine Biology",
    arrival_date: "2025-07-20",
    favorite_dish: "Currywurst & German Pretzels",
    languages_spoken: "German, English",
    languages_learning: "Indonesian",
    study_interests: "Oceanography, Ecosystem Conservation, Statistics",
  },
  {
    id: "p-9",
    name: "Elena Vancea",
    home_country: "Romania",
    home_city: "Bucharest",
    current_country: "Netherlands",
    current_city: "Amsterdam",
    university: "University of Amsterdam",
    bio: "Digital Culture & Media Communications. Biking along canals, photography, and finding foreign film lovers in Holland.",
    avatar_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    instagram: "elena_ams",
    whatsapp: "+31612345678",
    linkedin: "elena-vancea-media",
    twitter: null,
    website: null,
    is_buddy: true,
    major: "Media & Communications",
    arrival_date: "2025-09-01",
    favorite_dish: "Sarmale & Mamaliga",
    languages_spoken: "Romanian, English",
    languages_learning: "Dutch, German",
    study_interests: "Digital Media, Journalism, Cultural Studies",
  },
  {
    id: "p-10",
    name: "Gabriel Silva",
    home_country: "Brazil",
    home_city: "São Paulo",
    current_country: "Germany",
    current_city: "Berlin",
    university: "Humboldt University of Berlin",
    bio: "Economics & Public Policy master student. Love playing guitar, Brazilian samba nights, and discussing global trade policies.",
    avatar_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80",
    instagram: "gabi_berlin",
    whatsapp: "+4917612345678",
    linkedin: "gabriel-silva-econ",
    twitter: null,
    website: null,
    is_buddy: true,
    major: "Economics",
    arrival_date: "2025-10-01",
    favorite_dish: "Feijoada & Pão de Queijo",
    languages_spoken: "Portuguese, English, Spanish",
    languages_learning: "German",
    study_interests: "Macroeconomics, Public Policy, Econometrics",
  },
  {
    id: "p-11",
    name: "Priya Patel",
    home_country: "India",
    home_city: "Ahmedabad",
    current_country: "Canada",
    current_city: "Vancouver",
    university: "University of British Columbia (UBC)",
    bio: "Software Engineering co-op student at UBC. Coffee enthusiast, tech hacker, and always looking for weekend hiking group members!",
    avatar_url: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    instagram: "priya_ubc",
    whatsapp: "+16045550199",
    linkedin: "priya-patel-ubc",
    twitter: null,
    website: null,
    is_buddy: true,
    major: "Software Engineering",
    arrival_date: "2025-09-03",
    favorite_dish: "Dhokla & Pav Bhaji",
    languages_spoken: "Gujarati, Hindi, English",
    languages_learning: "French",
    study_interests: "Cloud Computing, Microservices, React",
  },
  {
    id: "p-12",
    name: "Yuki Tanaka",
    home_country: "Japan",
    home_city: "Kyoto",
    current_country: "United Kingdom",
    current_city: "Oxford",
    university: "University of Oxford",
    bio: "English Literature & Classical Philosophy. Tea ceremony host, rower at Christ Church College, and lover of antiquarian bookshops.",
    avatar_url: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80",
    instagram: "yuki_oxford",
    whatsapp: "+447700900555",
    linkedin: "yuki-tanaka-oxford",
    twitter: null,
    website: null,
    is_buddy: true,
    major: "English Literature",
    arrival_date: "2025-10-01",
    favorite_dish: "Matcha Kaiseki & Soba Noodles",
    languages_spoken: "Japanese, English",
    languages_learning: "Latin, German",
    study_interests: "Literary Theory, Victorian Novels, Ethics",
  },
];

export const DIVERSE_HANGOUTS: HangoutItem[] = [
  {
    id: "h-1",
    title: "Global Street Food & Cook-Off Night",
    details: "Bring a homemade dish from your country or help prepare authentic Indian Biryani and Italian Pasta together!",
    current_city: "Munich",
    date_time: "This Saturday • 6:30 PM",
    created_by_name: "Aarav Sharma",
    category: "cookoff",
    created_at: "2026-03-01T10:00:00Z",
  },
  {
    id: "h-2",
    title: "German-Mandarin & Spanish Tandem Circle",
    details: "Relaxed language exchange over coffee at Cafe Einstein. 30 mins Mandarin/Spanish, 30 mins English/German!",
    current_city: "Berlin",
    date_time: "Thursday • 5:00 PM",
    created_by_name: "Gabriel Silva",
    category: "tandem",
    created_at: "2026-03-02T14:30:00Z",
  },
  {
    id: "h-3",
    title: "TUM Computer Science Exam & Code Sprint",
    details: "Group revision session for AI & Data Structures. Laptops, whiteboard brainstorming, and fresh coffee!",
    current_city: "Munich",
    date_time: "Sunday • 2:00 PM",
    created_by_name: "Aarav Sharma",
    category: "study",
    created_at: "2026-03-03T09:15:00Z",
  },
  {
    id: "h-4",
    title: "Imperial & UCL Student Pub Quiz Night",
    details: "Fun trivia competition covering world geography, pop culture, and science. Team prizes included!",
    current_city: "London",
    date_time: "Friday • 7:00 PM",
    created_by_name: "Sophia Chen",
    category: "casual",
    created_at: "2026-03-04T16:00:00Z",
  },
  {
    id: "h-5",
    title: "Central Park Sunset Picnic & Frisbee",
    details: "Relaxing Sunday meetup for international students in NYC. Bring snacks, blankets, and good vibes!",
    current_city: "New York",
    date_time: "Sunday • 4:00 PM",
    created_by_name: "Mateo Rossi",
    category: "casual",
    created_at: "2026-03-05T11:20:00Z",
  },
];

export interface HometownStore {
  id: string;
  name: string;
  category: "Asian" | "Halal / Middle Eastern" | "Latin American" | "African / Caribbean" | "European / Bakery";
  address: string;
  city: string;
  country: string;
  lat: number;
  lng: number;
  phone: string;
  hours: string;
  priceLevel: "$" | "$$" | "$$$";
  specialties: string[];
  rating: number;
  reviewsCount: number;
  description: string;
}

export interface StudentHubCluster {
  id: string;
  areaName: string;
  city: string;
  country: string;
  lat: number;
  lng: number;
  studentCount: number;
  topCountries: string[];
  description: string;
  popularPlaces: string[];
}

export const HOMETOWN_STORES: HometownStore[] = [
  {
    id: "store-1",
    name: "Asia Land Market",
    category: "Asian",
    address: "Kantstraße 101, 10627 Berlin",
    city: "Berlin",
    country: "Germany",
    lat: 52.5065,
    lng: 13.3050,
    phone: "+49 30 3180 5511",
    hours: "Mon-Sat: 09:30 - 20:00",
    priceLevel: "$$",
    specialties: ["Ramen Noodles", "Gyoza Wrappers", "Matcha Powder", "Tofu", "Soya Sauce"],
    rating: 4.8,
    reviewsCount: 38,
    description: "Huge selection of authentic East Asian grocers, fresh produce, dumplings, and seasonings."
  },
  {
    id: "store-2",
    name: "Bollywood Spices & Groceries",
    category: "Halal / Middle Eastern",
    address: "Karlstraße 42, 80333 Munich",
    city: "Munich",
    country: "Germany",
    lat: 48.1432,
    lng: 11.5645,
    phone: "+49 89 5998 8123",
    hours: "Mon-Sat: 09:00 - 20:00",
    priceLevel: "$",
    specialties: ["Basmati Rice 5kg", "Garam Masala", "Paneer", "Halal Meats", "Atta Flour"],
    rating: 4.9,
    reviewsCount: 52,
    description: "Top-rated Indian grocery store with fresh halal meats, lentils, and authentic South Asian spices."
  },
  {
    id: "store-3",
    name: "Mercado Latino Supermercado",
    category: "Latin American",
    address: "Rua Augusta 450, São Paulo",
    city: "São Paulo",
    country: "Brazil",
    lat: -23.5505,
    lng: -46.6480,
    phone: "+55 11 3255 9012",
    hours: "Mon-Sat: 08:30 - 20:30",
    priceLevel: "$$",
    specialties: ["Harina PAN", "Dulce de Leche", "Tequila & Mezcal", "Tortillas", "Yerba Mate"],
    rating: 4.7,
    reviewsCount: 29,
    description: "Vibrant market stocked with Mexican tortillas, Colombian Harina PAN, Peruvian sauces, and snacks."
  },
  {
    id: "store-4",
    name: "Afro-Caribbean Market",
    category: "African / Caribbean",
    address: "Brixton Station Rd 12, London",
    city: "London",
    country: "United Kingdom",
    lat: 51.4625,
    lng: -0.1145,
    phone: "+44 20 7733 9812",
    hours: "Mon-Sat: 09:00 - 19:30",
    priceLevel: "$",
    specialties: ["Fresh Plantains", "Jollof Rice Seasoning", "Yams", "Scotch Bonnet Peppers", "Cassava"],
    rating: 4.9,
    reviewsCount: 44,
    description: "Authentic West African & Caribbean grocery supplier stocked with fresh yams, plantains, and spices."
  },
  {
    id: "store-5",
    name: "Boulangerie & Epicerie Parisienne",
    category: "European / Bakery",
    address: "Rue Saint-Denis 180, Paris",
    city: "Paris",
    country: "France",
    lat: 48.8665,
    lng: 2.3515,
    phone: "+33 1 42 36 78 90",
    hours: "Mon-Sun: 07:00 - 20:00",
    priceLevel: "$$",
    specialties: ["Artisanal Baguettes", "Croissants", "French Cheeses", "Wine", "Patisserie"],
    rating: 4.8,
    reviewsCount: 61,
    description: "Fresh daily French baguettes, imported cheeses, wines, and fine pastries recommended by students."
  }
];

export const STUDENT_HUBS: StudentHubCluster[] = [
  {
    id: "hub-1",
    areaName: "Kreuzberg & Neukölln Student Cluster",
    city: "Berlin",
    country: "Germany",
    lat: 52.4862,
    lng: 13.4244,
    studentCount: 68,
    topCountries: ["India", "Turkey", "Spain", "Brazil", "USA"],
    description: "Densely populated student district known for affordable shared flats (WGs), cafes, and 24/7 markets.",
    popularPlaces: ["Tempelhofer Feld", "Maybachufer Market", "Kottbusser Tor Cafes"]
  },
  {
    id: "hub-2",
    areaName: "Maxvorstadt University District",
    city: "Munich",
    country: "Germany",
    lat: 48.1500,
    lng: 11.5750,
    studentCount: 84,
    topCountries: ["India", "China", "Italy", "France", "Austria"],
    description: "Located surrounding TUM & LMU main campuses. High concentration of international student dorms and libraries.",
    popularPlaces: ["Englischer Garten", "TUM Main Library", "Türkenstraße Cafes"]
  },
  {
    id: "hub-3",
    areaName: "South Kensington & Bloomsbury Hub",
    city: "London",
    country: "United Kingdom",
    lat: 51.4988,
    lng: -0.1749,
    studentCount: 92,
    topCountries: ["China", "India", "USA", "France", "Nigeria"],
    description: "Surrounding Imperial College and UCL campuses. Dense international student housing and study lounges.",
    popularPlaces: ["Science Museum Library", "Exhibition Road", "Hyde Park"]
  }
];

