/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettleRouteImport } from './routes/_authenticated/settle'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated/marketplace'
import { Route as AuthenticatedInviteRouteImport } from './routes/_authenticated/invite'
import { Route as AuthenticatedDiscoverRouteImport } from './routes/_authenticated/discover'
import { Route as AuthenticatedChatsRouteImport } from './routes/_authenticated/chats'
import { Route as AuthenticatedActivitiesRouteImport } from './routes/_authenticated/activities'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettleRoute = AuthenticatedSettleRouteImport.update({
  id: '/settle',
  path: '/settle',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInviteRoute = AuthenticatedInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiscoverRoute = AuthenticatedDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatsRoute = AuthenticatedChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivitiesRoute = AuthenticatedActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activities': typeof AuthenticatedActivitiesRoute
  '/chats': typeof AuthenticatedChatsRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/invite': typeof AuthenticatedInviteRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settle': typeof AuthenticatedSettleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activities': typeof AuthenticatedActivitiesRoute
  '/chats': typeof AuthenticatedChatsRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/invite': typeof AuthenticatedInviteRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settle': typeof AuthenticatedSettleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/activities': typeof AuthenticatedActivitiesRoute
  '/_authenticated/chats': typeof AuthenticatedChatsRoute
  '/_authenticated/discover': typeof AuthenticatedDiscoverRoute
  '/_authenticated/invite': typeof AuthenticatedInviteRoute
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settle': typeof AuthenticatedSettleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/activities'
    | '/chats'
    | '/discover'
    | '/invite'
    | '/marketplace'
    | '/onboarding'
    | '/profile'
    | '/settle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/activities'
    | '/chats'
    | '/discover'
    | '/invite'
    | '/marketplace'
    | '/onboarding'
    | '/profile'
    | '/settle'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/activities'
    | '/_authenticated/chats'
    | '/_authenticated/discover'
    | '/_authenticated/invite'
    | '/_authenticated/marketplace'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/settle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settle': {
      id: '/_authenticated/settle'
      path: '/settle'
      fullPath: '/settle'
      preLoaderRoute: typeof AuthenticatedSettleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invite': {
      id: '/_authenticated/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof AuthenticatedInviteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discover': {
      id: '/_authenticated/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthenticatedDiscoverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats': {
      id: '/_authenticated/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activities': {
      id: '/_authenticated/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AuthenticatedActivitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivitiesRoute: typeof AuthenticatedActivitiesRoute
  AuthenticatedChatsRoute: typeof AuthenticatedChatsRoute
  AuthenticatedDiscoverRoute: typeof AuthenticatedDiscoverRoute
  AuthenticatedInviteRoute: typeof AuthenticatedInviteRoute
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettleRoute: typeof AuthenticatedSettleRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivitiesRoute: AuthenticatedActivitiesRoute,
  AuthenticatedChatsRoute: AuthenticatedChatsRoute,
  AuthenticatedDiscoverRoute: AuthenticatedDiscoverRoute,
  AuthenticatedInviteRoute: AuthenticatedInviteRoute,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettleRoute: AuthenticatedSettleRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
